# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    auth.login_success_handler:
        class: AppBundle\Security\LoginSuccessHandler
        arguments:
            - "@router"
            - "@security.authorization_checker"

#    workflow.customer_signup.guard.customer_signup_guard:
#        class: AppBundle\Event\Subscriber\CustomerSignUpGuard
#        arguments:
#            - "@session.flash_bag"
#            - "@security.authorization_checker"
#        tags:
#            - { name: kernel.event_subscriber }


    workflow.customer_signup.upgrade_customer_subscriber:
        class: AppBundle\Event\Subscriber\UpgradeCustomerSubscriber
        arguments:
            - "@workflow.customer_signup"
            - "@logger"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }